### ISSUE TITLE
Make compatible with IE11

### ISSUE THREAD

**Issue by justinjstark** [GirlsCodeLincoln/Website#1]
I used CSS grid on the new layout with a subgrid. IE11 uses an old CSS grid spec. To support it, we'll need to use ms- prefixes and be able to fall back to the old spec.

**Comment by troynguyen8** [comment]
The user of var() in the CSS is also not IE compatible. We may be able to use a CSS preprocessor to accomplish the same effect.

**Comment by justinjstark** [comment]
@troynguyen8 Yes. We are using Netlify which can run a build instead of just deploying the static site. At the same time, we probably don't need to fully support IE11 as long as the content is visible and usable (even if it's ugly).

**Comment by troynguyen8** [comment]
Before video discussion with website committee, planning on addressing this by moving away from CSS grid and using bootstrap column format
