### ISSUE TITLE
Add corporate sponsorship information page

### ISSUE THREAD

**Issue by justinjstark** [GirlsCodeLincoln/Website#2]
Put the document we have on Google Drive that we give to Lincoln organizations up as a page.

**Comment by troynguyen8** [comment]
@justinjstark Is this the donation page?
https://docs.google.com/document/d/1L1X583jowrO9-PhZqpPgxmk024ViIUgOg7Brw4q52Qs/edit#heading=h.sv6bx3gbq17q

**Comment by justinjstark** [comment]
Yep. Our fundraising team wants that up for pitches. It probably doesn't need to be on the main page but somewhere accessible when companies go to our website to learn more about us.

**Comment by justinjstark** [comment]
I wouldn't mind both but I think 1 is good for now. As we build out more "how to get involved" we can do 2.

**Comment by troynguyen8** [comment]
Sounds good, for the sake of this issue will just be adding a link to a pdf form of the google drive document linked above.
