### ISSUE TITLE
Add corporate sponsor logos to main page

### ISSUE THREAD

**Issue by justinjstark** [GirlsCodeLincoln/Website#4]
Currently: Makeshift, Fuse Coworking

**Comment by Jasbury2** [comment]
![makeshift logo](https://user-images.githubusercontent.com/32022606/47389121-8f95b300-d6d9-11e8-9897-88aeef9b5f55.png)
![fuse coworking](https://user-images.githubusercontent.com/32022606/47389123-915f7680-d6d9-11e8-99d5-40eb91e64953.png)

I'm not 100% positive that this is the correct makeshift logo, but I found these!

**Comment by justinjstark** [comment]
Probably this one for Makeshift:
[http://makeshiftlincoln.org/wp-content/uploads/2017/07/LOGO_navy_zzzz.png](http://makeshiftlincoln.org/wp-content/uploads/2017/07/LOGO_navy_zzzz.png)

**Comment by troynguyen8** [comment]
Closing - relevant PRs:

https://github.com/GirlsCodeLincoln/Website/pull/19
https://github.com/GirlsCodeLincoln/Website/pull/20
https://github.com/GirlsCodeLincoln/Website/pull/21
